FROM node:16

WORKDIR /usr/src/app

COPY app/package*.json ./
COPY app .
COPY graph/src/graph/schema.graphql ../graph/src/graph/schema.graphql

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
