version: '3.7'
services:
  graph:
    build:
      context: .
      dockerfile: Dockerfile.graph
    restart: always
    ports:
      - '4000:4000'
  web:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    restart: always
    ports:
      - '3000:3000'
