FROM node:16

ENV TZ="America/New_York"

RUN apk add tzdata
RUN cp /usr/share/zoneinfo/America/New_York /etc/localtime
RUN echo "America/New_York" > /etc/timezone

WORKDIR /usr/src/app

COPY graph/package*.json ./
COPY graph .

RUN npm install
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
