name: Build corinth container
defaults:
  run:
    shell: bash
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  IMAGE_NAME: anigenero-corinth-code-challenge
  REGISTRY: ghcr.io
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: setup
        run: ./setup.sh
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
      - run: docker-compose build
      - run: docker-compose push --ignore-push-failures
